name: VNC Server with ngrok

on:
  workflow_dispatch:

jobs:
  vnc-ngrok:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install VNC and Dependencies
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver jq

      - name: Configure VNC Server
        run: |
          mkdir -p ~/.vnc
          # Set VNC password to "123456"
          echo "123456" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          # Start VNC server on display :1 (port 5901)
          vncserver :1
          echo "VNC server started on display :1"

      - name: Download and Install ngrok
        run: |
          curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar -xz
          sudo mv ngrok /usr/local/bin/

      - name: Configure ngrok Authtoken
        run: |
          ngrok config add-authtoken 2umpyO1jqQBspvw8thvR72Vkr2H_6nPYdUqcYJZmvvGpM4mvg

      - name: Start ngrok for VNC (port 5901)
        run: |
          nohup ngrok tcp 5901 &
          sleep 10

      - name: Retrieve ngrok Public URL
        run: |
          # Query ngrok's local API for the public URL
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep Workflow Running
        run: |
          echo "VNC server and ngrok tunnel are running."
          sleep 1h
          
